# Generated by Django 4.2 on 2023-04-21 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AudioBookName',
            fields=[
                ('audioBookId', models.IntegerField(primary_key=True, serialize=False)),
                ('audiobookName', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Audio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audioName', models.CharField(max_length=255)),
                ('audioFile', models.FileField(upload_to='AudioUpload/')),
                ('bookName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audio', to='audio.audiobookname')),
            ],
        ),
    ]
