# Generated by Django 4.2 on 2023-04-21 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiobookname',
            name='audioBookImage',
            field=models.ImageField(default='', upload_to='ImageUpload/'),
            preserve_default=False,
        ),
    ]
