# Generated by Django 4.2 on 2023-04-21 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0002_audiobookname_audiobookimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='audio',
            name='author',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
